-- MySQL Script generated by MySQL Workbench
-- 01/10/16 17:57:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main` DEFAULT CHARACTER SET utf8 ;
USE `main` ;

-- -----------------------------------------------------
-- Table `main`.`Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Device` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SystemID` VARCHAR(64) NOT NULL,
  `CounterRequests` INT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Request` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CreatedAt` INT NOT NULL,
  `IDDeviceFK` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Request_Device1_idx` (`IDDeviceFK` ASC),
  CONSTRAINT `fk_Request_Device1`
    FOREIGN KEY (`IDDeviceFK`)
    REFERENCES `main`.`Device` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Event` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDRequestFK` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `idRequestFK_idx` (`IDRequestFK` ASC),
  CONSTRAINT `idRequestFK`
    FOREIGN KEY (`IDRequestFK`)
    REFERENCES `main`.`Request` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Location` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Radius` INT NOT NULL,
  `Longitude` DOUBLE NOT NULL,
  `Latitude` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`TypeRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`TypeRequest` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`LevelDanger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`LevelDanger` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Level` INT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Description` (
  `Title` VARCHAR(45) NULL,
  `ID` INT NOT NULL,
  `IDTypeRequestFK` INT NOT NULL,
  `IDLevelDangerFK` INT NOT NULL,
  `IDLocationFK` INT NOT NULL,
  INDEX `fk_Description_TypeRequest1_idx` (`IDTypeRequestFK` ASC),
  INDEX `fk_Description_Requests1_idx` (`ID` ASC),
  INDEX `fk_Description_LevelDanger1_idx` (`IDLevelDangerFK` ASC),
  PRIMARY KEY (`ID`),
  INDEX `fk_Description_Location1_idx` (`IDLocationFK` ASC),
  CONSTRAINT `fk_Description_TypeRequest1`
    FOREIGN KEY (`IDTypeRequestFK`)
    REFERENCES `main`.`TypeRequest` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Description_Requests1`
    FOREIGN KEY (`ID`)
    REFERENCES `main`.`Request` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Description_LevelDanger1`
    FOREIGN KEY (`IDLevelDangerFK`)
    REFERENCES `main`.`LevelDanger` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Description_Location1`
    FOREIGN KEY (`IDLocationFK`)
    REFERENCES `main`.`Location` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Photo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `URL` TEXT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`1` (
  `` INT NOT NULL,
  PRIMARY KEY (``))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
